// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type EmailVerification struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	OtpHash    string
	Attempts   int32
	ExpiresAt  pgtype.Timestamptz
	LastSentAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type PasswordReset struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	OtpHash    string
	Attempts   int32
	ExpiresAt  pgtype.Timestamptz
	LastSentAt pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type User struct {
	ID           uuid.UUID
	Email        string
	Name         string
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	IsVerified   bool
}
