// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: password_reset.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deletePasswordResetByUserID = `-- name: DeletePasswordResetByUserID :exec
DELETE FROM password_resets WHERE user_id = $1
`

func (q *Queries) DeletePasswordResetByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePasswordResetByUserID, userID)
	return err
}

const getPasswordResetByUserID = `-- name: GetPasswordResetByUserID :one
SELECT id, user_id, otp_hash, attempts, expires_at, last_sent_at, created_at FROM password_resets WHERE user_id = $1
`

func (q *Queries) GetPasswordResetByUserID(ctx context.Context, userID uuid.UUID) (PasswordReset, error) {
	row := q.db.QueryRow(ctx, getPasswordResetByUserID, userID)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OtpHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.LastSentAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementPasswordResetAttempts = `-- name: IncrementPasswordResetAttempts :one
UPDATE password_resets
SET attempts = attempts + 1
WHERE user_id = $1
RETURNING attempts
`

func (q *Queries) IncrementPasswordResetAttempts(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, incrementPasswordResetAttempts, userID)
	var attempts int32
	err := row.Scan(&attempts)
	return attempts, err
}

const upsertPasswordReset = `-- name: UpsertPasswordReset :one
INSERT INTO password_resets (user_id, otp_hash, attempts, expires_at, last_sent_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (user_id) DO UPDATE
SET otp_hash = EXCLUDED.otp_hash,
    attempts = EXCLUDED.attempts,
    expires_at = EXCLUDED.expires_at,
    last_sent_at = now()
RETURNING id, user_id, otp_hash, attempts, expires_at, last_sent_at, created_at
`

type UpsertPasswordResetParams struct {
	UserID    uuid.UUID
	OtpHash   string
	Attempts  int32
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) UpsertPasswordReset(ctx context.Context, arg UpsertPasswordResetParams) (PasswordReset, error) {
	row := q.db.QueryRow(ctx, upsertPasswordReset,
		arg.UserID,
		arg.OtpHash,
		arg.Attempts,
		arg.ExpiresAt,
	)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OtpHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.LastSentAt,
		&i.CreatedAt,
	)
	return i, err
}
