// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, name, password_hash)
VALUES ($1, $2, $3)
RETURNING id, email, name, password_hash, created_at, updated_at, is_verified
`

type CreateUserParams struct {
	Email        string
	Name         string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Name, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsVerified,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password_hash, created_at, updated_at, is_verified FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsVerified,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, password_hash, created_at, updated_at, is_verified FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsVerified,
	)
	return i, err
}

const setUserVerified = `-- name: SetUserVerified :exec
UPDATE users
SET is_verified = TRUE, updated_at = now()
WHERE id = $1
`

func (q *Queries) SetUserVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setUserVerified, id)
	return err
}

const updatePasswordHashAndVerify = `-- name: UpdatePasswordHashAndVerify :exec
UPDATE users
SET password_hash = $2, is_verified = TRUE, updated_at = now()
WHERE id = $1
`

type UpdatePasswordHashAndVerifyParams struct {
	ID           uuid.UUID
	PasswordHash string
}

func (q *Queries) UpdatePasswordHashAndVerify(ctx context.Context, arg UpdatePasswordHashAndVerifyParams) error {
	_, err := q.db.Exec(ctx, updatePasswordHashAndVerify, arg.ID, arg.PasswordHash)
	return err
}
