// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: verification.sql

package sqlcdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteVerificationByUserID = `-- name: DeleteVerificationByUserID :exec
DELETE FROM email_verifications WHERE user_id = $1
`

func (q *Queries) DeleteVerificationByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteVerificationByUserID, userID)
	return err
}

const getVerificationByUserID = `-- name: GetVerificationByUserID :one
SELECT id, user_id, otp_hash, attempts, expires_at, last_sent_at, created_at FROM email_verifications WHERE user_id = $1
`

func (q *Queries) GetVerificationByUserID(ctx context.Context, userID uuid.UUID) (EmailVerification, error) {
	row := q.db.QueryRow(ctx, getVerificationByUserID, userID)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OtpHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.LastSentAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementVerificationAttempts = `-- name: IncrementVerificationAttempts :one
UPDATE email_verifications
SET attempts = attempts + 1
WHERE user_id = $1
RETURNING attempts
`

func (q *Queries) IncrementVerificationAttempts(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, incrementVerificationAttempts, userID)
	var attempts int32
	err := row.Scan(&attempts)
	return attempts, err
}

const upsertVerification = `-- name: UpsertVerification :one
INSERT INTO email_verifications (user_id, otp_hash, attempts, expires_at, last_sent_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (user_id) DO UPDATE
SET otp_hash = EXCLUDED.otp_hash,
    attempts = EXCLUDED.attempts,
    expires_at = EXCLUDED.expires_at,
    last_sent_at = now()
RETURNING id, user_id, otp_hash, attempts, expires_at, last_sent_at, created_at
`

type UpsertVerificationParams struct {
	UserID    uuid.UUID
	OtpHash   string
	Attempts  int32
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) UpsertVerification(ctx context.Context, arg UpsertVerificationParams) (EmailVerification, error) {
	row := q.db.QueryRow(ctx, upsertVerification,
		arg.UserID,
		arg.OtpHash,
		arg.Attempts,
		arg.ExpiresAt,
	)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OtpHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.LastSentAt,
		&i.CreatedAt,
	)
	return i, err
}
